# This is an production ready docker compose that can be utilized with Coolify.
services:
  audaapp:
    restart: always
    ports:
      - 8888:8888
    build:
      dockerfile: app.Dockerfile
    environment:
      - AUDA_BACKEND_HOST=0.0.0.0
      - AUDA_BACKEND_PORT=8888
      - SERVICE_URL_BACKEND_8888
      - AUDA_BACKEND_WORKERS=2
    volumes:
      - ./data/data:/app/data
      - ./data/media:/app/media

  audaweb:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    restart: always
    build:
      dockerfile: web.Dockerfile
      args:
        - AUDA_BACKEND_URL=$SERVICE_URL_BACKEND
    ports:
      - 80:80
    environment:
      - AUDA_BACKEND_URL=$SERVICE_URL_BACKEND

  